version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/products:/app/static/products
    ports:
      - "80:80"
    depends_on:
      - fastapi

