version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    expose:
      - "8000:8000"  # Exponha a porta 8000 internamente
    volumes:
      - .:/app
    networks:
      - pi2

#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./static/products:/usr/share/nginx/html
#    ports:
#      - "80:80"
#    networks:
#      - pi2
#    depends_on:
#      - fastapi

  minio:
    image: minio/minio
    ports:
      - "9002:9002"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
volumes:

  minio_storage: { }

networks:

  pi2:
    driver: bridge

#version: '3'
#services:
#  fastapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
#    env_file:
#      - .env
#    ports:
#      - "80:8000"
#    volumes:
#      - .:/app
#
#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./static/products:/app/static/products
#    ports:
#      - "80:80"
#    depends_on:
#      - fastapi
