version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./img:/app/img  # Armazene o diretório de imagens no volume da aplicação
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://yourdbuser:yourdbpassword@db:5432/yourdbname
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"

  nginx_reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  nginx_image_server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx_image_server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data:
